name: Batch Video Builder Test

on:
    # Run Via a webhook only
    repository_dispatch:
        types: [video_builder_test]

jobs:
    run_test:
        if: ${{ github.event.client_payload.ffmpeg_control_config }}
        runs-on: ubuntu-latest
        steps:
          - env:
              CONFIG: ${{ github.event.client_payload.ffmpeg_control_config }}
            run: echo $CONFIG
