name: Batch Video Builder Test

on:
    # Run Via a webhook only
    repository_dispatch:
        types: [video_builder_test]

jobs:
    run_test:
        runs-on: ubuntu-latest
        steps:
            - name: run test
              run: |
                  echo "hello"
