# ╭───────────────────────────────────────────────────────────────────────────╮
# │                               REQUIREMENTS                                │
# ╰───────────────────────────────────────────────────────────────────────────╯
#
# Make sure the following SECRET variables are set to access your server.
# SSH_PASS        = Password to your server to upload video to.  
# SSH_USER        = Username to your server to upload video to.
# RCLONE_CONF_B64 = Configuration of rCLone to allow access to Google Drive.

name: 🎬 Video Builder

on:
  # Run Via a webhook only
  workflow_dispatch:
    inputs:
      config_b64:
        description: 'Base64 configuration for scriptflow'     
        required: true
      ssh_server:
        description: 'Settings for SSH to Server'  
      ssh_folder:
        description: 'Folder to save media to'  
      gdrive_folder:
        description: 'Folder to download from'  
        required: true
      return_webhook:
        description: 'Make.com webhook to trigger on finish'


jobs:

    build_video:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:



            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                                 INSTALL                                  │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



            # ╭───────────────────────────────────────────────────────╮
            # │             GENERATE A UNIQUE IDENTIFIER              │
            # ╰───────────────────────────────────────────────────────╯
            - name: Generate UUID
              id: generate_uuid
              run: |
                  echo "UUID=$(openssl rand -hex 6)" >> $GITHUB_ENV



            # ╭───────────────────────────────────────────────────────╮
            # │             GET CONTENTS OF CURRENT REPO              │
            # ╰───────────────────────────────────────────────────────╯
            - name: Checkout Repo
              uses: actions/checkout@v3

            

            # ╭───────────────────────────────────────────────────────╮
            # │        COPY ALL REPO SCRIPTS TO /usr/local/bin        │
            # ╰───────────────────────────────────────────────────────╯
            - name: Copy scripts to PATH
              run: |
                  sudo cp ./scripts/* /usr/local/bin      



            # ╭───────────────────────────────────────────────────────╮
            # │                    INSTALL YT-DLP                     │
            # ╰───────────────────────────────────────────────────────╯
            - name: Install YT-DLP
              continue-on-error: true
              run: |
                  sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
                  sudo chmod a+rx /usr/local/bin/yt-dlp



            # ╭───────────────────────────────────────────────────────╮
            # │                    INSTALL RCLONE                     │
            # ╰───────────────────────────────────────────────────────╯
            - name: Install rCLONE
              continue-on-error: true
              run: |
                sudo apt update
                sudo apt install rclone



            # ╭───────────────────────────────────────────────────────╮
            # │                    Install FFMPEG                     │
            # ╰───────────────────────────────────────────────────────╯
            - uses: FedericoCarboni/setup-ffmpeg@v2
            - name: Install FFMPEG
              run: |
                  cd /usr/local/bin
                  env
                  ln -s /opt/hostedtoolcache/ffmpeg/*/x64/ffmpeg ./ffmpeg
                  ln -s /opt/hostedtoolcache/ffmpeg/*/x64/ffprobe ./ffprobe   
                  


            # ╭───────────────────────────────────────────────────────╮
            # │               INSTALL FFMPEG SCRIPTFLOW               │
            # ╰───────────────────────────────────────────────────────╯
            - name: Install Scriptflow
              continue-on-error: true
              run: |
                  sudo git clone https://github.com/IORoot/ffmpeg__bash-scripts.git /tmp/scriptflow
                  sudo mv /tmp/scriptflow/*.sh /usr/local/bin
                  sudo chmod +x /usr/local/bin/*



            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                                SCRIPTFLOW                                │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


            - name: rclone copy videos onto runner
              continue-on-error: true
              run: | 
                  echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 --decode > rclone.conf
                  mkdir videos
                  rclone copy GDrive:${{ github.event.inputs.gdrive_folder }}/ ./videos --config rclone.conf 
                  ls -la ./videos


            # ╭───────────────────────────────────────────────────────╮
            # │  Run /usr/local/bin/scriptflow.sh with the config.json  │
            # ╰───────────────────────────────────────────────────────╯
            - name: Run ScriptFlow
              continue-on-error: true
              run: |

                  echo ${{ github.event.inputs.config_b64 }} | base64 --decode > ${GITHUB_WORKSPACE}/config.json

                  cd ${GITHUB_WORKSPACE}
                  mkdir -p ${GITHUB_WORKSPACE}/processed_video
                  export PATH=$PATH:$(pwd)
                  scriptflow.sh --config $(realpath ./config.json) -t

                  if [ -f output.mp4 ]; then
                    mv output.mp4 "${GITHUB_WORKSPACE}/processed_video/${UUID}_video.mp4"
                  fi

                  if [ -f ff_thumbnail-01.png ]; then
                    mv ff_thumbnail-01.png "${GITHUB_WORKSPACE}/processed_video/${UUID}_thumbnail.png"
                  fi

                  ls -la
                  ls -la ${GITHUB_WORKSPACE}/processed_video
                  


            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                               GOOGLE DRIVE                               │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



            - name: rclone copy result back to google drive
              run: | 
                  rclone copy ${GITHUB_WORKSPACE}/processed_video GDrive:${{ github.event.inputs.gdrive_folder }}/ --config rclone.conf 


            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                                WEBSERVER                                 │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



            # ╭───────────────────────────────────────────────────────╮
            # │        Copy the video and thumbnail to server         │
            # ╰───────────────────────────────────────────────────────╯
            # - name: Copy Video to Server
            #   if: env.webserver == 'true'
            #   run: |

            #       if [ -z "${{ env.ssh_server }}" ]; then
            #         echo "ssh_server is not set or is empty. Exiting."
            #         exit 1
            #       fi

            #       if [ -z "${{ env.ssh_folder }}" ]; then
            #         echo "ssh_folder is not set or is empty. Exiting."
            #         exit 1
            #       fi
                  
            #       mkdir ~/.ssh
            #       ssh-keyscan -H ${{env.ssh_server}} >> ~/.ssh/known_hosts

            #       SOURCE_DIR="./processed_video"
            #       TARGET_DIR="${ssh_folder}/${{ github.event.action }}"

            #       sshpass -p '${{secrets.SSH_PASS}}' ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{secrets.SSH_USER}}@${{env.ssh_server}} "mkdir -p ${TARGET_DIR}"
            #       cd ${SOURCE_DIR}
            #       sshpass -p '${{secrets.SSH_PASS}}' scp -v -p -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null * ${{secrets.SSH_USER}}@${{env.ssh_server}}:${TARGET_DIR}
      

            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                                 RELEASE                                  │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



            # ╭───────────────────────────────────────────────────────╮
            # │                   CREATE A RELEASE                    │
            # ╰───────────────────────────────────────────────────────╯
            # - name: Create a Release
            #   run: |
            #       GDRIVE_FILE_ID=$(cat GDRIVE_FILE_META | jq -r '.[].ID')

            #       echo $GDRIVE_FILE_ID

            #       create_release.sh \
            #       --target ${{env.release_rest_api_url}} \
            #       --token ${{env.release_rest_api_token}} \
            #       --schedule "${{env.release_schedule}}" \
            #       --title "${{ github.event.action }} - ${UUID}" \
            #       --content "" \
            #       --gdrive ${GDRIVE_FILE_ID} \
            #       --video ${{env.output_url}}/${{ github.event.action }}/${UUID}_video.mp4 \
            #       --thumbnail ${{env.output_url}}/${{ github.event.action }}/${UUID}_thumbnail.png




            # ╭───────────────────────────────────────────────────────╮
            # │     DEBUGGER - Use to SSH into the Github Runner      │
            # ╰───────────────────────────────────────────────────────╯
            # SSH ----------------------
            # - name: Setup upterm session
            #   uses: lhotari/action-upterm@v1
            # SSH ----------------------