name: Batch Video Builder Test

# Run with a CURL request:
#
# curl                                                            \
# -X POST                                                         \
# -H "Accept: application/vnd.github+json"                        \
# -H "Authorization: Bearer GITHUB_PAT_KEY"                       \
# -H "X-GitHub-Api-Version: 2022-11-28"                           \
#     https://api.github.com/repos/ioroot/ffmpeg__bash-scripts/dispatches \
#     -d '{"event_type":"run_autoflip","client_payload":{         \
#             "GDRIVE_FOLDER":  "FOLDER/IN/GDRIVE/TO/USE",        \
#         }                                                       \

on:
    # Run Via a webhook
    repository_dispatch:
        types: [video_builder_test]

jobs:
    run_test:
        runs-on: ubuntu-latest
        steps:
            - name: run test
              run: |
                  echo "hello"
