# ╭───────────────────────────────────────────────────────────────────────────╮
# │                               REQUIREMENTS                                │
# ╰───────────────────────────────────────────────────────────────────────────╯
#
# Make sure the following SECRET variables are set to access your server.
# SSH_PASS        = Password to your server to upload video to.  
# SSH_USER        = Username to your server to upload video to.
# RCLONE_CONF_B64 = Configuration of rCLone to allow access to Google Drive.

name: 🎬 Video Builder

on:
  # Run Via a webhook only
  workflow_dispatch:
    inputs:
      config_b64:
        description: 'Base64 configuration for scriptflow'     
        required: true
      gdrive_folder:
        description: 'Folder to download from'  
      ssh_server:
        description: 'Settings for SSH to Server'  
        required: false
        default: '' 
      ssh_folder:
        description: 'Folder to save media to' 
        required: false
        default: '' 
      return_webhook:
        description: 'Make.com webhook to trigger on finish'


jobs:

    build_video:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:



            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                                 INSTALL                                  │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



            # ╭───────────────────────────────────────────────────────╮
            # │             GENERATE A UNIQUE IDENTIFIER              │
            # ╰───────────────────────────────────────────────────────╯
            - name: Generate UUID
              id: generate_uuid
              run: |
                  echo "UUID=$(openssl rand -hex 6)" >> $GITHUB_ENV



            # ╭───────────────────────────────────────────────────────╮
            # │             GET CONTENTS OF CURRENT REPO              │
            # ╰───────────────────────────────────────────────────────╯
            - name: Checkout Repo
              uses: actions/checkout@v3

            

            # ╭───────────────────────────────────────────────────────╮
            # │        COPY ALL REPO SCRIPTS TO /usr/local/bin        │
            # ╰───────────────────────────────────────────────────────╯
            - name: Copy scripts to PATH
              run: |
                  sudo cp ./scripts/* /usr/local/bin      



            # ╭───────────────────────────────────────────────────────╮
            # │                    INSTALL YT-DLP                     │
            # ╰───────────────────────────────────────────────────────╯
            - name: Install YT-DLP
              continue-on-error: true
              run: |
                  sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
                  sudo chmod a+rx /usr/local/bin/yt-dlp



            # ╭───────────────────────────────────────────────────────╮
            # │                    INSTALL RCLONE                     │
            # ╰───────────────────────────────────────────────────────╯
            - name: Install rCLONE
              continue-on-error: true
              run: |
                sudo apt update
                sudo apt install rclone



            # ╭───────────────────────────────────────────────────────╮
            # │                    Install FFMPEG                     │
            # ╰───────────────────────────────────────────────────────╯
            - uses: FedericoCarboni/setup-ffmpeg@v2
            - name: Install FFMPEG
              run: |
                  cd /usr/local/bin
                  env
                  ln -s /opt/hostedtoolcache/ffmpeg/*/x64/ffmpeg ./ffmpeg
                  ln -s /opt/hostedtoolcache/ffmpeg/*/x64/ffprobe ./ffprobe   
                  


            # ╭───────────────────────────────────────────────────────╮
            # │               INSTALL FFMPEG SCRIPTFLOW               │
            # ╰───────────────────────────────────────────────────────╯
            - name: Install Scriptflow
              continue-on-error: true
              run: |
                  sudo git clone https://github.com/IORoot/ffmpeg__bash-scripts.git /tmp/scriptflow
                  sudo mv /tmp/scriptflow/*.sh /usr/local/bin
                  sudo chmod +x /usr/local/bin/*



            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                                SCRIPTFLOW                                │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


            - name: rclone copy videos onto runner
              continue-on-error: true
              if: ${{ github.event.inputs.gdrive_folder != '' }}
              run: | 
                  echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 --decode > rclone.conf
                  mkdir videos
                  rclone copy GDrive:${{ github.event.inputs.gdrive_folder }}/ ./videos --config rclone.conf 
                  ls -la ./videos


            # ╭───────────────────────────────────────────────────────╮
            # │  Run /usr/local/bin/scriptflow.sh with the config.json  │
            # ╰───────────────────────────────────────────────────────╯
            - name: Run ScriptFlow
              run: |

                  echo ${{ github.event.inputs.config_b64 }} | base64 --decode > ${GITHUB_WORKSPACE}/config.json

                  cd ${GITHUB_WORKSPACE}
                  mkdir -p ${GITHUB_WORKSPACE}/${UUID}_processed_video
                  export PATH=$PATH:$(pwd)
                  scriptflow.sh --config $(realpath ./config.json) -t

                  if [ -f output.mp4 ]; then
                    mv output.mp4 "${GITHUB_WORKSPACE}/${UUID}_processed_video/video.mp4"
                  fi

                  if [ -f ff_thumbnail-01.png ]; then
                    mv ff_thumbnail-01.png "${GITHUB_WORKSPACE}/${UUID}_processed_video/thumbnail.png"
                  fi

                  ls -la
                  ls -la ${GITHUB_WORKSPACE}/${UUID}_processed_video
                  


            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                               GOOGLE DRIVE                               │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



            - name: rclone copy result back to google drive
              if: ${{ github.event.inputs.gdrive_folder != '' }}
              continue-on-error: true
              run: | 
                  rclone copy ${GITHUB_WORKSPACE}/${UUID}_processed_video GDrive:${{ github.event.inputs.gdrive_folder }}/${UUID}_processed_video --config rclone.conf 


            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                                WEBSERVER                                 │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



            # ╭───────────────────────────────────────────────────────╮
            # │        Copy the video and thumbnail to server         │
            # ╰───────────────────────────────────────────────────────╯
            - name: Copy Video to Server
              continue-on-error: true
              if: ${{ github.event.inputs.ssh_server != '' && github.event.inputs.ssh_folder != '' }}
              run: |
               
                  mkdir ~/.ssh
                  ssh-keyscan -H ${{github.event.inputs.ssh_server}} >> ~/.ssh/known_hosts

                  TARGET_DIR="${{ github.event.inputs.ssh_folder }}/${{ github.event.action }}/${{ github.event.inputs.gdrive_folder }}"

                  sshpass -p '${{secrets.SSH_PASS}}' ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{secrets.SSH_USER}}@${{github.event.inputs.ssh_server}} "mkdir -p ${TARGET_DIR}"

                  cd ./${UUID}_processed_video
                  sshpass -p '${{secrets.SSH_PASS}}' scp -v -p -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null * ${{secrets.SSH_USER}}@${{github.event.inputs.ssh_server}}:${TARGET_DIR}
      


            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │               Once the results are complete, send webhook                │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
        
        
        
            - name: Trigger Return Webhook
              continue-on-error: true
              run: |
                curl -X POST \
                  -H "Content-Type: text/plain" \
                  -d "${{ github.event.inputs.gdrive_folder }}/${UUID}_processed_video/video.mp4" \
                  ${{ github.event.inputs.return_webhook }}



            # ╭──────────────────────────────────────────────────────────────────────────╮
            # │                                                                          │░
            # │                                 RELEASE                                  │░
            # │                                                                          │░
            # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



            # ╭───────────────────────────────────────────────────────╮
            # │                   CREATE A RELEASE                    │
            # ╰───────────────────────────────────────────────────────╯
            # - name: Create a Release
            #   run: |
            #       GDRIVE_FILE_ID=$(cat GDRIVE_FILE_META | jq -r '.[].ID')

            #       echo $GDRIVE_FILE_ID

            #       create_release.sh \
            #       --target ${{github.event.inputs.release_rest_api_url}} \
            #       --token ${{github.event.inputs.release_rest_api_token}} \
            #       --schedule "${{github.event.inputs.release_schedule}}" \
            #       --title "${{ github.event.action }} - ${UUID}" \
            #       --content "" \
            #       --gdrive ${GDRIVE_FILE_ID} \
            #       --video ${{github.event.inputs.output_url}}/${{ github.event.action }}/video.mp4 \
            #       --thumbnail ${{github.event.inputs.output_url}}/${{ github.event.action }}/thumbnail.png




            # ╭───────────────────────────────────────────────────────╮
            # │     DEBUGGER - Use to SSH into the Github Runner      │
            # ╰───────────────────────────────────────────────────────╯
            # SSH ----------------------
            # - name: Setup upterm session
            #   uses: lhotari/action-upterm@v1
            # SSH ----------------------