name: Batch Video Builder Test

on:
    # Run Via a webhook only
    repository_dispatch:
        types: [video_builder_test]

jobs:
    run_test:
        if: ${{ github.event.client_payload.ffmpeg_control_config_b64 }}
        runs-on: ubuntu-latest
        steps:
          
          - name: set payload
            env:
              CONFIG: ${{ github.event.client_payload.ffmpeg_control_config_b64 }}
            run: echo $CONFIG | | base64 --decode > config.json

          - name: Print decoded payload
            run: |
              cat config.json